// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDeeNoCrUPGibghrhfMr9VYB28f6gfZjw',
    appId: '1:621290376467:web:7d443ea2db6ae472225ee6',
    messagingSenderId: '621290376467',
    projectId: 'flavora-flutter-app',
    authDomain: 'flavora-flutter-app.firebaseapp.com',
    storageBucket: 'flavora-flutter-app.firebasestorage.app',
    measurementId: 'G-00S7KG4GSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXpAAKCS98uqX3anTYvj3RSzUY_11B9M',
    appId: '1:621290376467:android:83d5da33d6ec21df225ee6',
    messagingSenderId: '621290376467',
    projectId: 'flavora-flutter-app',
    storageBucket: 'flavora-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3c6hb3YsUiK5r1DH78r78Bj936JZYs_8',
    appId: '1:621290376467:ios:a408b3ca27c9b267225ee6',
    messagingSenderId: '621290376467',
    projectId: 'flavora-flutter-app',
    storageBucket: 'flavora-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flavora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3c6hb3YsUiK5r1DH78r78Bj936JZYs_8',
    appId: '1:621290376467:ios:a408b3ca27c9b267225ee6',
    messagingSenderId: '621290376467',
    projectId: 'flavora-flutter-app',
    storageBucket: 'flavora-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flavora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDeeNoCrUPGibghrhfMr9VYB28f6gfZjw',
    appId: '1:621290376467:web:406d3bc2c11a4e5f225ee6',
    messagingSenderId: '621290376467',
    projectId: 'flavora-flutter-app',
    authDomain: 'flavora-flutter-app.firebaseapp.com',
    storageBucket: 'flavora-flutter-app.firebasestorage.app',
    measurementId: 'G-F783EZ23J8',
  );
}
